product-intro-header-text: Achieve More with In-Depth with telemore.ai
product-intro-colored-text: "services"
product-intro-header-subtext: Telemore.ai seamlessly integrates with your employees screens to provide real-time insights into their workflow and productivity
product-intro-header-text: The next-generation productivity
product-intro-colored-text: "analytics tool."
product-intro-header-subtext: Telemore.ai seamlessly integrates with your employees screens to provide real-time insights into their workflow and productivity
product-intro-image: /assets/image/service-banner2.png
product-intro-button-text1: Lorem ipsum
product-intro-button-link1:

product-service-header: Lorem ipsum dolor sit amet
product-service-description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. viverra maecenas accumsan lacus vel facilisis."
product-service-list:
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service1.png
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service2.png
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service3.png

product-integration-header: "Lorem ipsum dolor sit amet"
product-integration-description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
product-integration-bg: /assets/image/integrations-bg-landscape.png
product-integration-list:
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon1.png
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon2.png
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon3.png

product-support-header: Lorem ipsum dolor
product-support-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.
product-support-image: /assets/image/support.png

    