brand-logo-text: "telemore.ai"
nav:
  - slugid: 1
    text: Home
    link: /
    isDropDown:
  - slugid: 2
    text: Product Details
    link:
    isDropDown: true
    subMenu:
      - text: What is telemore
        link: /services/
        desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere nec sapien vitae vestibulum.
      - text: What is telemore
        link: /services/
        desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere nec sapien vitae vestibulum.
      - text: What is telemore
        link: /services/
        desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere nec sapien vitae vestibulum.
    
  - slugid: 3
    text: Pricing
    link: /pricing/
    isDropDown:
  - slugid: 4
    text: Blog
    link: /blogs/
    isDropDown:
  - slugid: 5
    text: Contact Us
    link: /contact-us/
    isDropDown:

footer-text: Copyright © 2025
footer-policy: Privacy Policy
footer-policy-link: /privacy/
footer-tos: Terms of Service
footer-tos-link: /terms/

intro-header-text: Generative AI Employee Productivity
intro-colored-text: "Monitoring"
intro-header-subtext: Telemore integrates with employee's work devices to provide task tracking and user activity visibility, with actionable recommendations and insights.
intro-image: /assets/image/hero-image.png

intro-button-text1: Get Started For Free
intro-button-link1: https://telemore.app

intro-button-text2: Request a demo
intro-button-href: https://calendly.com/telemore
intro-button-link2: 

home-company-header: Trusted by over 500 global companies
home-company-list:
  - image: /assets/image/company-placeholder.svg
    link: #
  - image: /assets/image/company-placeholder.svg
    link: #
  - image: /assets/image/company-placeholder.svg
    link: #
  - image: /assets/image/company-placeholder.svg
    link: #


service-header: Insights That Matter, Not Just Metrics
service-description: "Unlike traditional tools that overwhelm you with raw data and metrics, Telemore offers higher-level summarization of what employees did, and coaching on how to perform better. Our platform helps you optimize workflows and boost productivity without the noise."
service-list:
  - subheader: what does this do?
    title: Unlike other employee monitoring firms,
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service1.png
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service2.png
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service3.png

integration-header: "Built with security "
integration-description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
integration-bg: /assets/image/integrations-bg-landscape.png
integration-list:
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon1.png
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon2.png
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon3.png

support-header: Lorem ipsum dolor
support-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.
support-image: /assets/image/support.png



    