brand-logo-text: "Telemore AI"
nav:
  - slugid: 1
    text: Home
    link: /
    isDropDown:
  - slugid: 2
    text: Product Details
    link:
    isDropDown: true
    subMenu:
      - text: How it Works
        link: /how-it-works/
        desc: Discover how Telemore seamlessly integrates with employees’ devices to provide actionable insights and optimize productivity
      - text: Security & Privacy
        link: /security/
        desc: Learn how Telemore ensures your data stays secure while maintaining transparency and privacy for your team
      - text: FAQs
        link: /faq/
        desc: Find answers to commonly asked questions about Telemore’s features, functionality, and setup process
    
  - slugid: 3
    text: Pricing
    link: /pricing/
    isDropDown:
  - slugid: 4
    text: Blog
    link: /blogs/
    isDropDown:
  - slugid: 5
    text: Contact Us
    link: /contact-us/
    isDropDown:

footer-text: Copyright © 2025
footer-policy: Privacy Policy
footer-policy-link: /privacy/
footer-tos: Terms of Service
footer-tos-link: /terms/

home-intro-header-text: Generative AI Employee Productivity
home-intro-colored-text: "Monitoring"
home-intro-header-subtext: Telemore installs on Employee Laptops, and provides Insights on Tasks and User Activity (Proof of Work) with Actionable Recommendations
home-intro-image: /assets/image/hero-image.png

home-intro-button-text1: Get Started for Free
home-intro-button-link1: https://telemore.app

home-intro-button-text2: Request a Demo
home-intro-button-href: https://calendly.com/telemore
home-intro-button-link2: 

home-company-header: Built with Industry Experience From
home-company-list:
  - image: /assets/image/aws_logo.png
    link: #
  - image: /assets/image/sig_logo.png
    link: #
  - image: /assets/image/capone_logo.png
    link: #
  - image: /assets/image/tr_logo.png
    link: #
  - image: /assets/image/emerson_logo.png
    link: #


home-service-header: Insights that Matter, not just Metrics
home-service-description: "Go beyond raw metrics with Telemore. Our platform transforms complex data into actionable insights and personalized coaching, empowering your team to perform better and optimize workflows—without the clutter of traditional tools"
home-service-list:
  - subheader: Managers
    title: See employee activity logs with AI feedback
    description: Get detailed insights into workflows with AI-driven feedback. Using an LLM model and secure access to screens and telemetry, Telemore delivers precise summaries and actionable recommendations to boost productivity
    image: /assets/image/service1.png
  - subheader: Employees
    title: Control monitoring and get help with tasks
    description: Toggle the monitoring to start working timer and get personalized guidance and recommendations on their tasks. Screen Recordings are used to monitor actions
    image: /assets/image/service2.png
  - subheader: Managers
    title: Setup alerts and rules to enforce compliance & productivity
    description: Built-in detectors set up guardrails for your employees when they are on working time. Receive alerts on infractions to provide visibility
    image: /assets/image/service3.png

home-integration-header: "Built with Security and Privacy First"
home-integration-description: "Telemore prioritizes data protection and compliance, delivering secure solutions that maintain transparency and meet the highest privacy standards"
home-integration-bg: /assets/image/integrations-bg-landscape.png
home-integration-list:
  - title: End-to-End Data Encryption
    description: All data (stored & in-transit) is encrypted using industry-leading standards such as AES-256 and TLS 1.3, ensuring sensitive information is safeguarded against unauthorized access.
    icon: /assets/image/icon1.png
  - title: Privacy Adherence
    description: We respect employee's privacy—we never record the webcam or microphone. Most of our monitoring centers around screenshot video data and metadata from running processes to provide the input to insights generated.
    icon: /assets/image/icon2.png
  - title: SOC 2 Type II/ ISO 27001 Certification In-Progress
    description: Estimated for mid-2025. We are currently working with our compliance specialist to document procedures and submit evidence of controls for the auditor.
    icon: /assets/image/icon3.png

home-support-header: Why use Telemore
home-support-description: At Telemore, we prioritize empowering businesses with tools that enhance productivity, maintain transparency, and respect employee privacy. Designed with innovation and security in mind, our platform integrates seamlessly into your workflow to deliver actionable insights that drive success.
home-support-image: /assets/image/support.png



    