brand-logo-text: "telemore.ai"
nav:
  - slugid: 1
    text: Home
    link: /
    isDropDown:
  - slugid: 2
    text: Product Details
    link:
    isDropDown: true
    subMenu:
      - text: What is telemore
        link: /services/
        desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere nec sapien vitae vestibulum.
      - text: What is telemore
        link: /services/
        desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere nec sapien vitae vestibulum.
      - text: What is telemore
        link: /services/
        desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere nec sapien vitae vestibulum.
    
  - slugid: 3
    text: Pricing
    link:
    isDropDown:
  - slugid: 4
    text: Blog
    link: /blogs/
    isDropDown:
  - slugid: 5
    text: Contact Us
    link:
    isDropDown:

footer-text: Copyright © 2024
footer-policy: Privacy Policy
footer-policy-link: /privacy/
footer-tos: Terms of Service
footer-tos-link: /terms/

intro-header-text: The next-generation productivity
intro-colored-text: "analytics tool."
intro-header-subtext: Telemore.ai seamlessly integrates with your employees screens to provide real-time insights into their workflow and productivity
intro-image: /assets/image/hero-image.png
intro-button-text1: Lorem ipsum
intro-button-link1:

service-header: Lorem ipsum dolor sit amet
service-description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. viverra maecenas accumsan lacus vel facilisis."
service-list:
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service1.png
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service2.png
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service3.png

integration-header: "Lorem ipsum dolor sit amet"
integration-description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
integration-bg: /assets/image/integrations-bg-landscape.png
integration-list:
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon1.png
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon2.png
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon3.png

support-header: Lorem ipsum dolor
support-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.
support-image: /assets/image/support.png



    