brand-logo-text: "telemore.ai"
nav:
  - slugid: 1
    text: Home
    link: /
    isDropDown:
  - slugid: 2
    text: Product Details
    link:
    isDropDown: true
    subMenu:
      - text: What is telemore
        link: /services/
        desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere nec sapien vitae vestibulum.
      - text: What is telemore
        link: /services/
        desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere nec sapien vitae vestibulum.
      - text: What is telemore
        link: /services/
        desc: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla posuere nec sapien vitae vestibulum.
    
  - slugid: 3
    text: Pricing
    link: /pricing/
    isDropDown:
  - slugid: 4
    text: Blog
    link: /blogs/
    isDropDown:
  - slugid: 5
    text: Contact Us
    link: /contact-us/
    isDropDown:

footer-text: Copyright © 2025
footer-policy: Privacy Policy
footer-policy-link: /privacy/
footer-tos: Terms of Service
footer-tos-link: /terms/

home-intro-header-text: Generative AI Employee Productivity
home-intro-colored-text: "Monitoring"
home-intro-header-subtext: Telemore integrates with employee's work devices to provide task tracking and user activity visibility, with actionable recommendations and insights.
home-intro-image: /assets/image/hero-image.png

home-intro-button-text1: Get Started For Free
home-intro-button-link1: https://telemore.app

home-intro-button-text2: Request a demo
home-intro-button-href: https://calendly.com/telemore
home-intro-button-link2: 

home-company-header: Built with Industry Experience From
home-company-list:
  - image: /assets/image/aws_logo.png
    link: #
  - image: /assets/image/sig_logo.png
    link: #
  - image: /assets/image/capone_logo.png
    link: #
  - image: /assets/image/tr_logo.png
    link: #
  - image: /assets/image/emerson_logo.png
    link: #


home-service-header: Insights That Matter, Not Just Metrics
home-service-description: "Unlike traditional tools that overwhelm you with raw data and metrics, Telemore offers higher-level summarization of what employees did, and coaching on how to perform better. Our platform helps you optimize workflows and boost productivity without the noise."
home-service-list:
  - subheader: what does this do?
    title: Unlike other employee monitoring firms,
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service1.png
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service2.png
  - subheader: Lorem ipsum dolor
    title: Lorem ipsum dolor sit amet
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. 
    image: /assets/image/service3.png

home-integration-header: "Built with security "
home-integration-description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
home-integration-bg: /assets/image/integrations-bg-landscape.png
home-integration-list:
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon1.png
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon2.png
  - title: Lorem ipsum dolor
    description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    icon: /assets/image/icon3.png

home-support-header: Lorem ipsum dolor
home-support-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis.
home-support-image: /assets/image/support.png



    